### ISSUE TITLE
Call to undefined method Backend\VueComponents\Modal::addJsBundle()

### ISSUE THREAD

**Issue by jacksun101** [cydrickn/octobercms-backendskin#11]
There is an error with the latest OctoberCMS v2.2.x. Any suggestion?

<img width="1200" alt="image" src="https://user-images.githubusercontent.com/417021/175246615-69c0feca-a4fb-40bd-ae5b-6bc95aeba680.png">

Reproduce steps..
1. Install the latest octobercms 2.x. `composer create-project october/october myoctober "^2.0"`
2. Install backendskin plugin 1.2.1. `php artisan plugin:install cyd293.backendskin`
3. Error shows up.

**Comment by cydrickn** [comment]
can you put here the whole logs, so that i can check further, and also if you can also add the plugins that you have install for me to investigate it.

**Comment by prhost** [comment]
Same problem here, Samuel checked with me yesterday this error and it seems that the problem is in the `AssetMaker.php` trait that the plugin overwrites.

**Comment by cydrickn** [comment]
The new major version 2.0.0 is now released, the fix is to fix the compatibility with version 2 and 3, but it will break version 1.
