### ISSUE TITLE
This request has been blocked; the content must be served over HTTPS.

### ISSUE THREAD

**Issue by jacksun101** [cydrickn/octobercms-backendskin#13]
I've been using the latest version of backendskin plugin for a couple days. It is working well. However, there is an issue of being compatible with HTTPS. I've tried a simple investigation and here is my summary for your reference.

<img width="1350" alt="Pasted Graphic 1" src="https://user-images.githubusercontent.com/417021/179327565-67ed093b-48aa-44c2-92cc-663abfdd81ca.png">

> Mixed Content: The page at 'https://DOMAIN/' was loaded over HTTPS, but requested an insecure image 'http://DOMAIN/themes/demo/assets/images/cms-template-diagram@2x.png'. This request has been blocked; the content must be served over HTTPS.

**October CMS version: v2.2.32**

Installed Plugins
**Cyd293.BackendSkin   1.2.1
October.Demo         1.0.1**

.env Setting
**LINK_POLICY=secure**

Reproduce steps:
- Install the latest OctoberCMS v2.x
- Install the latest BackendSkin plugin v1.2.1
- Updated the LINK_POLICY to **secure**.

And by removing or disabling the BackendSkin plugin, OctoberCMS can be back to normal. For example, .env setting as below.
DISABLE_PLUGINS="Cyd293.BackendSkin"

One more thing that could be worth mentioning is the following code section. The code, `Url::asset($asset);` seems not returning correct url with HTTPS.

File location: /plugins/cyd293/backendskin/traits/AssetMaker.php
Line number 336

<img width="668" alt="image" src="https://user-images.githubusercontent.com/417021/179328581-5ed3f7e7-3689-4600-95df-289d33b2bee7.png">

**Comment by cydrickn** [comment]
This was already fixed in version v2.0.2

https://github.com/cydrickn/octobercms-backendskin/commit/adcee6fcce1dfba8c0b78e116047872d6d67b6c9
