### ISSUE TITLE
when using backendhelper on octobercms3 release 3.1.26 with php 8.0.23 I get this error on backend model edit

### ISSUE THREAD

**Issue by msomma** [cydrickn/octobercms-backendskin#15]
array_key_exists(): Argument #2 ($array) must be of type array, string given

I debugged the laravel array helper class get the string 'build' instead of an array from plugin backendhelper

**Comment by msomma** [comment]
error is caused by traits assetmaker
function makeAssets  renderAssetAttributes  gives error array_key_exists(): Argument https://github.com/cydrickn/octobercms-backendskin/issues/2 ($array) must be of type array, string given when is processing 'build'

**Comment by cydrickn** [comment]
This is now fix in version 2.1.1
