### ISSUE TITLE
Update AssetMaker.php

### ISSUE THREAD

**Issue by Tony-S** [cydrickn/octobercms-backendskin#7]
AssetMaker trait needs updating with changes in modules/system/traits/AssetMaker.php. Specifically it  doesn't handle assets being passed in an array e.g. in a component  `$this->addCss('assets/css/uploader.css'); `works but `$this->addCss(['assets/css/uploader.css']);` doesn't. See https://github.com/octobercms/october/commit/aeb7616d063121d47cfb5aefe07fa9524e4a522b (but there could be other changes).

**Comment by cydrickn** [comment]
Hi @Tony-S,
I will check this and test.

**Comment by Tony-S** [comment]
Thanks. I've updated the copy of AssetMaker.php in your plugin by adding your changes back into a latest version of AssetMaker and all is working fine now front and backend.

**Comment by cydrickn** [comment]
Thanks, will you create a Pull Request for this?

**Comment by cydrickn** [comment]
Hi @Tony-S
I already push the fix for this.

I will include this with version v1.1.1

**Comment by Tony-S** [comment]
Thanks!
